// Next.js 16 "proxy" (formerly middleware). Runs on the Node.js runtime.
//
// Route guard.
//
// Presence check only. We trust that a cookie exists because the browser
// sent the user through the BFF login flow; actual validation happens on
// the backend for every API call. A browser with a forged cookie just
// gets a page that can't load its own data.
//
// Paths that always pass through:
//   /login                  the unauth'd entry point
//   /api/session/*          login, refresh, logout, me
//   /_next/*                Next asset pipeline
//   /favicon.ico, /robots.txt, /images/*
//   /sw.js, /manifest.json  PWA installable bits (must load pre-login)
//   /icons/*, /screenshots/* manifest-referenced assets
//   /.well-known/*          Digital Asset Links. Google and Android fetch
//                           assetlinks.json with no cookie; it must return 200
//                           with no redirect. It is generated by the API
//                           (GET /api/client/assetlinks.json) from the passkey
//                           settings, so this path is proxied there.
//
// Everything else requires at least a refresh cookie. The access cookie
// can be expired or missing; the client-side fetch wrapper will hit
// /api/session/refresh to recover.
//
// Single-origin routing. The web server is the only port a user needs to
// expose (LAN, reverse proxy, or one Cloudflare Tunnel rule). Requests that
// belong to the backends are proxied from here:
//   /stream/*                               -> Stream Gateway (STREAM_ORIGIN)
//   /api/* that is not a BFF path           -> API (API_ORIGIN)
//   /api/* carrying a Bearer token or a     -> API (native app, signed
//     signed `sig` query                         lock-screen art / downloads)
// Browser requests to the BFF paths keep going through the Next route
// handlers so tokens never reach the browser. A tunnel or reverse proxy that
// already routes /api and /stream straight to the backends never hits this.

import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { ACCESS_COOKIE, REFRESH_COOKIE } from "@/lib/server-env";
import { requestProto, siteOriginFromHeaders } from "@/lib/origin";
import { buildForwardHeaders, PEER_HEADER, TRUST_HEADER } from "@/lib/forward-headers";
import { isForbiddenCrossOrigin, securityHeaders } from "@/lib/security-headers";

const API_ORIGIN = process.env.API_ORIGIN ?? "http://127.0.0.1:8001";
const STREAM_ORIGIN = process.env.STREAM_ORIGIN ?? "http://127.0.0.1:8002";

// Paths served by Next route handlers (cookie -> bearer swap).
const BFF_PREFIXES = [
  "/api/session/",
  "/api/library/",
  "/api/stream/",
  "/api/admin/",
  "/api/art/",
  "/api/requests/",
  // Live channel (SSE) + command POST. The browser's EventSource cannot set an
  // Authorization header, so these go through the Next BFF route which swaps
  // the httpOnly cookie for the Bearer token. A native app sending its own
  // Bearer is routed straight to the API by backendFor() below.
  "/api/live/",
];

const ASSETLINKS_PATH = "/.well-known/assetlinks.json";

// Length-safe, time-independent string compare. Avoids leaking the secret
// length or matching position through early-exit timing on the trust check.
function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

// The request is trusted (its client-IP headers are honoured and forwarded on)
// only when it carries the shared secret the front door (Caddy, written by
// Setup) injects, and only when the env secret is actually set. With no secret
// configured nothing is trusted, which is the safe default: a direct LAN
// browser can never mark itself trusted. Next 16's proxy cannot read the client
// socket peer IP, so a shared secret header is the only sound signal here.
function isTrustedProxyHop(req: NextRequest): boolean {
  const secret = process.env.TRUSTED_PROXY_SECRET ?? "";
  if (!secret) return false;
  const sent = req.headers.get(TRUST_HEADER) ?? "";
  return timingSafeEqual(sent, secret);
}

function proxyTo(req: NextRequest, origin: string) {
  const path =
    req.nextUrl.pathname === ASSETLINKS_PATH
      ? "/api/client/assetlinks.json"
      : req.nextUrl.pathname + req.nextUrl.search;
  const target = new URL(path, origin);
  // Tell the backend which origin the client used (so the absolute URLs it
  // signs point back at this server) via the sanitised, allowlisted origin,
  // never the raw browser header. Client-IP headers are forwarded only from our
  // own front door, or (via the launcher's stamped socket peer) set to the real
  // LAN peer; a direct LAN browser's forged CF-Connecting-IP / X-Forwarded-* are
  // stripped. The peer header's value is passed straight into the helper, and
  // launcherActive is the unforgeable process-level signal the launcher sets.
  // See lib/forward-headers.ts and server-wrapper.js.
  const headers = buildForwardHeaders(req.headers, {
    siteOrigin: siteOriginFromHeaders(req.headers),
    proto: requestProto(req.headers),
    trusted: isTrustedProxyHop(req),
    peer: req.headers.get(PEER_HEADER),
    launcherActive: process.env.F7FIVE0_LAUNCHER === "1",
  });
  return NextResponse.rewrite(target, { request: { headers } });
}

function backendFor(req: NextRequest): string | null {
  const { pathname, searchParams } = req.nextUrl;
  if (pathname.startsWith("/stream/")) return STREAM_ORIGIN;
  if (pathname === ASSETLINKS_PATH) return API_ORIGIN;
  if (!pathname.startsWith("/api/")) return null;
  if (pathname.startsWith("/api/session/")) return null;
  // The live SSE stream is served at exactly /api/live (no trailing slash),
  // which the /api/live/ prefix would miss; treat it as a BFF path too.
  const isBff =
    pathname === "/api/live" || BFF_PREFIXES.some((p) => pathname.startsWith(p));
  if (!isBff) return API_ORIGIN;
  const auth = req.headers.get("authorization") ?? "";
  if (auth.toLowerCase().startsWith("bearer ")) return API_ORIGIN;
  if (searchParams.has("sig")) return API_ORIGIN;
  return null;
}

const PUBLIC_PREFIXES = [
  "/login",
  "/api/session/",
  "/_next/",
  "/images/",
  "/icons/",
  "/screenshots/",
  "/.well-known/",
];
const PUBLIC_FILES = new Set([
  "/favicon.ico",
  "/robots.txt",
  "/sw.js",
  "/manifest.json",
  "/icon.svg",
]);

export function proxy(req: NextRequest) {
  const { pathname, search } = req.nextUrl;

  // SEC-P1-5: HSTS only when the request genuinely arrived over HTTPS (or the
  // configured public address is https). Every response proxy() returns gets
  // the security headers via secure().
  const https =
    requestProto(req.headers) === "https" ||
    (process.env.PUBLIC_URL ?? "").startsWith("https://");
  const secure = (res: NextResponse): NextResponse => {
    for (const [k, v] of Object.entries(securityHeaders({ https }))) {
      res.headers.set(k, v);
    }
    return res;
  };

  // SEC-P1-5: CSRF defense in depth. A cookie-authed, state-changing BFF call
  // whose Origin is not ours is rejected before it reaches a route handler.
  // siteOriginFromHeaders is the one sanitised definition of "us".
  const selfOrigin = siteOriginFromHeaders(req.headers);
  const hasBearer = (req.headers.get("authorization") ?? "")
    .toLowerCase()
    .startsWith("bearer ");
  if (
    isForbiddenCrossOrigin({
      method: req.method,
      pathname,
      origin: req.headers.get("origin"),
      selfOrigin,
      hasBearer,
    })
  ) {
    return secure(
      new NextResponse(JSON.stringify({ detail: "bad_origin" }), {
        status: 403,
        headers: { "content-type": "application/json" },
      }),
    );
  }

  const backend = backendFor(req);
  if (backend) return secure(proxyTo(req, backend));

  if (PUBLIC_FILES.has(pathname)) return secure(NextResponse.next());
  for (const prefix of PUBLIC_PREFIXES) {
    if (pathname.startsWith(prefix)) return secure(NextResponse.next());
  }

  const hasSession =
    req.cookies.has(ACCESS_COOKIE) || req.cookies.has(REFRESH_COOKIE);
  if (hasSession) return secure(NextResponse.next());

  // Build the redirect target fresh from the incoming request's authority.
  // Cloning req.nextUrl carries Next's bind address (HOSTNAME=127.0.0.1,
  // PORT=3001) and its port persists even when we overwrite .host, which
  // produces a Location like https://media.example.com:3001/login that
  // the tunnel will not serve. The shared helper sanitises and allowlists
  // the forwarded Host / X-Forwarded-Proto so a forged header can't redirect
  // off-site or inject into the Location (SEC-P1-1).
  const url = new URL(siteOriginFromHeaders(req.headers));
  url.pathname = "/login";
  // Round-trip the original destination so we can bounce back after login.
  // Skip for API routes; those don't benefit from the redirect hint.
  if (!pathname.startsWith("/api/")) {
    url.searchParams.set("next", pathname + (search || ""));
  }
  return secure(NextResponse.redirect(url));
}

export const config = {
  // Run on all paths except Next internals. The handler above decides
  // which of those paths are actually public.
  //
  // api/admin/updates/upload is skipped on purpose: it carries a whole Setup
  // exe, and Next buffers at most 10 MB of a request body that goes through
  // this proxy (experimental.proxyClientMaxBodySize), which would cut the file
  // off. Its route handler streams the body to the API and makes the same-origin
  // check itself; the API requires the admin bearer and password.
  matcher: ["/((?!_next/static|_next/image|favicon.ico|robots.txt|api/admin/updates/upload).*)"],
};
