// Next.js 16 "proxy" (formerly middleware). Runs on the Node.js runtime.
//
// Route guard.
//
// Presence check only. We trust that a cookie exists because the browser
// sent the user through the BFF login flow; actual validation happens on
// the backend for every API call. A browser with a forged cookie just
// gets a page that can't load its own data.
//
// Paths that always pass through:
//   /login                  the unauth'd entry point
//   /api/session/*          login, refresh, logout, me
//   /_next/*                Next asset pipeline
//   /favicon.ico, /robots.txt, /images/*
//   /sw.js, /manifest.json  PWA installable bits (must load pre-login)
//   /icons/*, /screenshots/* manifest-referenced assets
//   /.well-known/*          Digital Asset Links. Google and Android fetch
//                           assetlinks.json with no cookie; it must return 200
//                           with no redirect. It is generated by the API
//                           (GET /api/client/assetlinks.json) from the passkey
//                           settings, so this path is proxied there.
//
// Everything else requires at least a refresh cookie. The access cookie
// can be expired or missing; the client-side fetch wrapper will hit
// /api/session/refresh to recover.
//
// Single-origin routing. The web server is the only port a user needs to
// expose (LAN, reverse proxy, or one Cloudflare Tunnel rule). Requests that
// belong to the backends are proxied from here:
//   /stream/*                               -> Stream Gateway (STREAM_ORIGIN)
//   /api/* that is not a BFF path           -> API (API_ORIGIN)
//   /api/* carrying a Bearer token or a     -> API (native app, signed
//     signed `sig` query                         lock-screen art / downloads)
// Browser requests to the BFF paths keep going through the Next route
// handlers so tokens never reach the browser. A tunnel or reverse proxy that
// already routes /api and /stream straight to the backends never hits this.

import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { ACCESS_COOKIE, REFRESH_COOKIE } from "@/lib/server-env";

const API_ORIGIN = process.env.API_ORIGIN ?? "http://127.0.0.1:8001";
const STREAM_ORIGIN = process.env.STREAM_ORIGIN ?? "http://127.0.0.1:8002";

// Paths served by Next route handlers (cookie -> bearer swap).
const BFF_PREFIXES = [
  "/api/session/",
  "/api/library/",
  "/api/stream/",
  "/api/admin/",
  "/api/art/",
  "/api/requests/",
  // Live channel (SSE) + command POST. The browser's EventSource cannot set an
  // Authorization header, so these go through the Next BFF route which swaps
  // the httpOnly cookie for the Bearer token. A native app sending its own
  // Bearer is routed straight to the API by backendFor() below.
  "/api/live/",
];

const ASSETLINKS_PATH = "/.well-known/assetlinks.json";

function proxyTo(req: NextRequest, origin: string) {
  const path =
    req.nextUrl.pathname === ASSETLINKS_PATH
      ? "/api/client/assetlinks.json"
      : req.nextUrl.pathname + req.nextUrl.search;
  const target = new URL(path, origin);
  const headers = new Headers(req.headers);
  // Tell the backend which origin the client used so the absolute URLs it
  // signs (HLS, subtitles, art, downloads) point back at this server.
  headers.set(
    "x-forwarded-host",
    req.headers.get("x-forwarded-host") ?? req.headers.get("host") ?? req.nextUrl.host,
  );
  headers.set(
    "x-forwarded-proto",
    req.headers.get("x-forwarded-proto") ?? req.nextUrl.protocol.replace(":", ""),
  );
  return NextResponse.rewrite(target, { request: { headers } });
}

function backendFor(req: NextRequest): string | null {
  const { pathname, searchParams } = req.nextUrl;
  if (pathname.startsWith("/stream/")) return STREAM_ORIGIN;
  if (pathname === ASSETLINKS_PATH) return API_ORIGIN;
  if (!pathname.startsWith("/api/")) return null;
  if (pathname.startsWith("/api/session/")) return null;
  // The live SSE stream is served at exactly /api/live (no trailing slash),
  // which the /api/live/ prefix would miss; treat it as a BFF path too.
  const isBff =
    pathname === "/api/live" || BFF_PREFIXES.some((p) => pathname.startsWith(p));
  if (!isBff) return API_ORIGIN;
  const auth = req.headers.get("authorization") ?? "";
  if (auth.toLowerCase().startsWith("bearer ")) return API_ORIGIN;
  if (searchParams.has("sig")) return API_ORIGIN;
  return null;
}

const PUBLIC_PREFIXES = [
  "/login",
  "/api/session/",
  "/_next/",
  "/images/",
  "/icons/",
  "/screenshots/",
  "/.well-known/",
];
const PUBLIC_FILES = new Set([
  "/favicon.ico",
  "/robots.txt",
  "/sw.js",
  "/manifest.json",
  "/icon.svg",
]);

export function proxy(req: NextRequest) {
  const { pathname, search } = req.nextUrl;

  const backend = backendFor(req);
  if (backend) return proxyTo(req, backend);

  if (PUBLIC_FILES.has(pathname)) return NextResponse.next();
  for (const prefix of PUBLIC_PREFIXES) {
    if (pathname.startsWith(prefix)) return NextResponse.next();
  }

  const hasSession =
    req.cookies.has(ACCESS_COOKIE) || req.cookies.has(REFRESH_COOKIE);
  if (hasSession) return NextResponse.next();

  // Build the redirect target fresh from the incoming request's authority.
  // Cloning req.nextUrl carries Next's bind address (HOSTNAME=127.0.0.1,
  // PORT=3001) and its port persists even when we overwrite .host, which
  // produces a Location like https://media.example.com:3001/login that
  // the tunnel will not serve. Trust the Host and X-Forwarded-Proto
  // headers the tunnel forwards and construct a clean URL.
  const hostHeader = req.headers.get("host") ?? req.nextUrl.host;
  const protoHeader =
    req.headers.get("x-forwarded-proto") ??
    req.nextUrl.protocol.replace(":", "");
  const url = new URL(`${protoHeader}://${hostHeader}`);
  url.pathname = "/login";
  // Round-trip the original destination so we can bounce back after login.
  // Skip for API routes; those don't benefit from the redirect hint.
  if (!pathname.startsWith("/api/")) {
    url.searchParams.set("next", pathname + (search || ""));
  }
  return NextResponse.redirect(url);
}

export const config = {
  // Run on all paths except Next internals. The handler above decides
  // which of those paths are actually public.
  matcher: ["/((?!_next/static|_next/image|favicon.ico|robots.txt).*)"],
};
