; F7FIVE0 Setup (Inno Setup 6).
;
; Build with installer\build-dist.ps1, which assembles installer\dist\ and
; then runs:  ISCC /DAppVersion=1.0.0 /DAppVersionNumeric=1.0.0 F7FIVE0.iss
;
; The wizard only collects answers. installer\install.ps1 does the actual
; work (prerequisites, database, services), so a scripted install and a
; wizard install behave the same.

#ifndef AppVersion
  #define AppVersion "0.0.0-dev"
#endif
#ifndef AppVersionNumeric
  #define AppVersionNumeric "0.0.0"
#endif

[Setup]
; Never change AppId: upgrades find the existing install by it.
AppId={{C3BE51D0-9C50-4B20-8C7D-CC3FCE9C32FE}
AppName=F7FIVE0
AppVersion={#AppVersion}
AppVerName=F7FIVE0 {#AppVersion}
AppPublisher=F7FIVE0
VersionInfoVersion={#AppVersionNumeric}
DefaultDirName=C:\F7FIVE0
UsePreviousAppDir=yes
DirExistsWarning=no
DisableProgramGroupPage=yes
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0.17763
OutputDir=Output
OutputBaseFilename=F7FIVE0-Setup-{#AppVersion}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
; Branding generated by installer\branding-src\generate-branding.mjs from
; design\logos (honeycomb mark on a white plate; black, hive red and white
; only). PNG plus scaled sizes for 100% to 200% DPI; Inno 6.3+ reads PNG and
; picks the closest size. Icons are a multi-size .ico.
WizardImageFile=branding\wizard-image.png,branding\wizard-image-125.png,branding\wizard-image-150.png,branding\wizard-image-200.png
WizardSmallImageFile=branding\wizard-small.png,branding\wizard-small-125.png,branding\wizard-small-150.png,branding\wizard-small-200.png
SetupIconFile=branding\f7five0.ico
LicenseFile=dist\LICENSE
CloseApplications=no
UninstallDisplayName=F7FIVE0
; The installed copy of the icon (shipped in dist\installer by build-dist.ps1)
; so the Apps list shows the F7FIVE0 mark after install.
UninstallDisplayIcon={app}\installer\f7five0.ico

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; Flags: unchecked

[Files]
Source: "dist\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion

[InstallDelete]
; Code folders are replaced wholesale on upgrade so removed files do not
; linger. Settings (.env), data\, and the Python venv are left alone.
Type: filesandordirs; Name: "{app}\web"
Type: filesandordirs; Name: "{app}\backend\app"
Type: filesandordirs; Name: "{app}\backend\alembic"

[INI]
Filename: "{app}\F7FIVE0.url"; Section: "InternetShortcut"; Key: "URL"; String: "http://localhost:{code:GetPort}"

[Icons]
Name: "{autoprograms}\F7FIVE0"; Filename: "{app}\F7FIVE0.url"
Name: "{autodesktop}\F7FIVE0"; Filename: "{app}\F7FIVE0.url"; Tasks: desktopicon
Name: "{autoprograms}\F7FIVE0 logs"; Filename: "{app}\logs"
Name: "{autoprograms}\F7FIVE0 settings (.env)"; Filename: "notepad.exe"; Parameters: """{app}\.env"""

[Run]
Filename: "{app}\F7FIVE0.url"; Description: "Open F7FIVE0 in your browser"; Flags: postinstall shellexec nowait skipifsilent; Check: SetupSucceeded

[UninstallRun]
Filename: "powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\installer\uninstall.ps1"" -InstallDir ""{app}"""; Flags: runhidden waituntilterminated; RunOnceId: "RemoveF7FIVE0Services"

[UninstallDelete]
; Runtime pieces setup downloaded. Your .env and data\ folder are kept so a
; reinstall picks up where you left off; delete them by hand to start fresh.
Type: filesandordirs; Name: "{app}\runtime"
Type: filesandordirs; Name: "{app}\bin"
Type: filesandordirs; Name: "{app}\backend\.venv"
Type: filesandordirs; Name: "{app}\logs"
Type: files; Name: "{app}\F7FIVE0.url"

[Code]
var
  // A query page with our own Browse buttons: Inno's directory page refuses
  // blank entries, and every media folder here is optional.
  MediaPage: TInputQueryWizardPage;
  AdminPage: TInputQueryWizardPage;
  PgPage: TInputQueryWizardPage;
  NetPage: TInputOptionWizardPage;
  OptionsPage: TInputQueryWizardPage;
  PortsPage: TInputQueryWizardPage;
  TmdbLink: TNewStaticText;
  InstallFailed: Boolean;

function IsUpgrade: Boolean;
begin
  Result := FileExists(AddBackslash(WizardDirValue) + '.env');
end;

function PostgresInstalled: Boolean;
begin
  if IsWin64 then
    Result := RegKeyExists(HKLM64, 'SOFTWARE\PostgreSQL\Installations')
      or DirExists(ExpandConstant('{commonpf64}\PostgreSQL'))
  else
    Result := RegKeyExists(HKLM, 'SOFTWARE\PostgreSQL\Installations');
end;

function ReadEnvPort: String;
var
  Lines: TArrayOfString;
  I: Integer;
begin
  Result := '';
  if LoadStringsFromFile(AddBackslash(WizardDirValue) + '.env', Lines) then
    for I := 0 to GetArrayLength(Lines) - 1 do
      if Pos('WEB_PORT=', Lines[I]) = 1 then
        Result := Trim(Copy(Lines[I], 10, 10));
end;

function GetPort(Param: String): String;
begin
  Result := '';
  if IsUpgrade then
    Result := ReadEnvPort;
  if (Result = '') and (PortsPage <> nil) then
    Result := Trim(PortsPage.Values[0]);
  if Result = '' then
    Result := '3001';
end;

function OptionalPortOk(S: String): Boolean;
var
  P: Integer;
begin
  Result := True;
  if Trim(S) <> '' then
  begin
    P := StrToIntDef(Trim(S), 0);
    Result := (P >= 1024) and (P <= 65535);
  end;
end;

function JsonEscape(S: String): String;
begin
  Result := S;
  StringChangeEx(Result, '\', '\\', True);
  StringChangeEx(Result, '"', '\"', True);
end;

function JsonPair(Key, Value: String; Last: Boolean): String;
begin
  Result := '  "' + Key + '": "' + JsonEscape(Value) + '"';
  if not Last then
    Result := Result + ',';
  Result := Result + #13#10;
end;

procedure TmdbLinkClick(Sender: TObject);
var
  ErrorCode: Integer;
begin
  // Setup runs elevated; open the page as the signed-in user so their
  // default browser (and its sign-in) is used. ShellExec as admin can do nothing.
  if not ShellExecAsOriginalUser('open', 'https://www.themoviedb.org/settings/api', '', '', SW_SHOWNORMAL, ewNoWait, ErrorCode) then
    MsgBox('Could not open your browser. Go to https://www.themoviedb.org/settings/api to get a key.', mbInformation, MB_OK);
end;

// Each media box holds one folder or several separated by ";". "Add..."
// appends the chosen folder instead of replacing what is there, so a library
// can span drives or a NAS share. install.ps1 and the server read the list.
function LastFolder(const List: String): String;
var
  P: Integer;
begin
  Result := Trim(List);
  P := Pos(';', Result);
  while P > 0 do
  begin
    Result := Trim(Copy(Result, P + 1, Length(Result)));
    P := Pos(';', Result);
  end;
end;

function HasFolder(const List, Dir: String): Boolean;
begin
  Result := Pos(';' + Lowercase(Dir) + ';', ';' + Lowercase(List) + ';') > 0;
end;

procedure BrowseMediaClick(Sender: TObject);
var
  I: Integer;
  Dir, List, Norm: String;
begin
  I := TNewButton(Sender).Tag;
  List := Trim(MediaPage.Values[I]);
  Norm := List;
  StringChangeEx(Norm, '; ', ';', True);
  Dir := LastFolder(List);
  if BrowseForFolder('Choose a folder F7FIVE0 should scan:', Dir, False) then
  begin
    Dir := RemoveBackslashUnlessRoot(Dir);
    if List = '' then
      MediaPage.Values[I] := Dir
    else if not HasFolder(Norm, Dir) then
      MediaPage.Values[I] := List + '; ' + Dir;
  end;
end;

procedure InitializeWizard;
var
  I: Integer;
  Btn: TNewButton;
begin
  MediaPage := CreateInputQueryPage(wpSelectDir,
    'Media folders', 'Where is your media?',
    'Pick the folders F7FIVE0 should scan. Leave any of them blank to skip it. ' +
    'Click Add again to use more than one folder for a library (they are separated by ;). ' +
    'Network paths such as \\nas\media\Movies work too.' + #13#10#13#10 +
    'Already use Radarr, Sonarr, or Lidarr? You can connect them later in the settings file.');
  MediaPage.Add('Movies:', False);
  MediaPage.Add('TV shows:', False);
  MediaPage.Add('Music:', False);
  MediaPage.Add('Music videos:', False);
  for I := 0 to 3 do
  begin
    Btn := TNewButton.Create(MediaPage);
    Btn.Parent := MediaPage.Surface;
    Btn.Caption := 'Add...';
    Btn.Tag := I;
    Btn.Width := ScaleX(75);
    Btn.Height := MediaPage.Edits[I].Height + ScaleY(2);
    Btn.Top := MediaPage.Edits[I].Top - ScaleY(1);
    Btn.Left := MediaPage.SurfaceWidth - Btn.Width;
    Btn.Anchors := [akTop, akRight];
    Btn.OnClick := @BrowseMediaClick;
    MediaPage.Edits[I].Width := Btn.Left - ScaleX(10) - MediaPage.Edits[I].Left;
  end;

  AdminPage := CreateInputQueryPage(MediaPage.ID,
    'Admin account', 'Create your F7FIVE0 account',
    'This account runs the server and can invite everyone else.');
  AdminPage.Add('Username (lowercase letters, digits, . _ -):', False);
  AdminPage.Add('Password (8 or more characters):', True);
  AdminPage.Add('Confirm password:', True);
  AdminPage.Values[0] := 'admin';

  PgPage := CreateInputQueryPage(AdminPage.ID,
    'PostgreSQL', 'PostgreSQL is already installed on this PC',
    'F7FIVE0 stores its library in PostgreSQL. Enter the password of the "postgres" ' +
    'account so Setup can create a separate F7FIVE0 database. The password is used once and not saved.');
  PgPage.Add('postgres password:', True);

  NetPage := CreateInputOptionPage(PgPage.ID,
    'Access', 'Who can reach F7FIVE0?',
    'F7FIVE0 always works on this PC. Choose whether other devices at home can use it too.' + #13#10#13#10 +
    'Away from home: once F7FIVE0 is running, sign in and go to Admin > Remote access. ' +
    'It walks you through Tailscale, Cloudflare, or port forwarding while you watch.',
    False, False);
  NetPage.Add('Let phones, TVs, and other computers on my home network connect');
  NetPage.Values[0] := True;

  OptionsPage := CreateInputQueryPage(NetPage.ID,
    'Optional extras', 'Both can be left blank',
    'TMDB API key: posters and descriptions for movies and shows. It is free: make a TMDB account, ' +
    'then request a key under Settings > API (link below). No key yet? Skip it and add it later ' +
    'in F7FIVE0 under Admin > Metadata.' + #13#10 +
    'Contact email: sent to MusicBrainz with music lookups, as their rules ask.');
  OptionsPage.Add('TMDB API key:', False);
  OptionsPage.Add('Contact email:', False);
  TmdbLink := TNewStaticText.Create(OptionsPage);
  TmdbLink.Parent := OptionsPage.Surface;
  TmdbLink.Caption := 'Get a free TMDB API key (themoviedb.org)';
  TmdbLink.Cursor := crHand;
  TmdbLink.Font.Color := clHighlight;
  TmdbLink.Font.Style := [fsUnderline];
  TmdbLink.Top := OptionsPage.Edits[1].Top + OptionsPage.Edits[1].Height + ScaleY(14);
  TmdbLink.Left := OptionsPage.Edits[1].Left;
  TmdbLink.OnClick := @TmdbLinkClick;

  PortsPage := CreateInputQueryPage(OptionsPage.ID,
    'Ports (advanced)', 'Most people keep these as they are',
    'Web port: the one port browsers, phones, and the app connect to (http://this-pc:3001). ' +
    'Change it only if another program already uses 3001.' + #13#10 +
    'API and stream ports are internal (this PC only). Leave them blank and Setup uses 8001 and 8002, ' +
    'or the next free ports.');
  PortsPage.Add('Web port:', False);
  PortsPage.Add('API port (blank = automatic):', False);
  PortsPage.Add('Stream port (blank = automatic):', False);
  PortsPage.Values[0] := '3001';
end;

procedure CurPageChanged(CurPageID: Integer);
var
  Summary: AnsiString;
begin
  if CurPageID = wpFinished then
  begin
    if InstallFailed then
      Exit;
    // install.ps1 writes a short summary (addresses, home network access,
    // anything that still needs doing).
    if LoadStringFromFile(ExpandConstant('{app}\logs\setup-summary.txt'), Summary) then
    begin
      WizardForm.FinishedLabel.Caption := String(Summary);
      WizardForm.FinishedLabel.AutoSize := False;
      WizardForm.FinishedLabel.Height := WizardForm.FinishedPage.Height - WizardForm.FinishedLabel.Top - ScaleY(70);
      WizardForm.RunList.Top := WizardForm.FinishedPage.Height - ScaleY(60);
    end;
  end;
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := False;
  if IsUpgrade and ((PageID = MediaPage.ID) or (PageID = AdminPage.ID) or (PageID = PgPage.ID)
      or (PageID = NetPage.ID) or (PageID = OptionsPage.ID) or (PageID = PortsPage.ID)) then
    Result := True
  else if (PageID = PgPage.ID) and not PostgresInstalled then
    Result := True;
end;

function ValidUsername(S: String): Boolean;
var
  I: Integer;
  C: Char;
begin
  Result := (Length(S) >= 3) and (Length(S) <= 64);
  if Result then
    for I := 1 to Length(S) do
    begin
      C := S[I];
      if not (((C >= 'a') and (C <= 'z')) or ((C >= '0') and (C <= '9')) or (C = '.') or (C = '_') or (C = '-')) then
        Result := False;
    end;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  Port: Integer;
begin
  Result := True;
  if CurPageID = AdminPage.ID then
  begin
    AdminPage.Values[0] := Lowercase(Trim(AdminPage.Values[0]));
    if not ValidUsername(AdminPage.Values[0]) then
    begin
      MsgBox('Usernames are 3 to 64 characters: lowercase letters, digits, dot, dash, underscore.', mbError, MB_OK);
      Result := False;
    end
    else if Length(AdminPage.Values[1]) < 8 then
    begin
      MsgBox('Please use a password of at least 8 characters.', mbError, MB_OK);
      Result := False;
    end
    else if AdminPage.Values[1] <> AdminPage.Values[2] then
    begin
      MsgBox('The passwords do not match.', mbError, MB_OK);
      Result := False;
    end;
  end
  else if CurPageID = PgPage.ID then
  begin
    if PgPage.Values[0] = '' then
    begin
      MsgBox('Enter the "postgres" password. If you do not know it, see INSTALL.md (Existing PostgreSQL).', mbError, MB_OK);
      Result := False;
    end;
  end
  else if CurPageID = PortsPage.ID then
  begin
    Port := StrToIntDef(Trim(PortsPage.Values[0]), 0);
    if (Port < 1024) or (Port > 65535) then
    begin
      MsgBox('Pick a web port between 1024 and 65535 (3001 is fine).', mbError, MB_OK);
      Result := False;
    end
    else if not OptionalPortOk(PortsPage.Values[1]) or not OptionalPortOk(PortsPage.Values[2]) then
    begin
      MsgBox('API and stream ports are optional. If you fill one in, use a number between 1024 and 65535.', mbError, MB_OK);
      Result := False;
    end;
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ResultCode: Integer;
begin
  // Stop running services so their files can be replaced on upgrade.
  Exec(ExpandConstant('{sys}\net.exe'), 'stop F7FIVE0-Web', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec(ExpandConstant('{sys}\net.exe'), 'stop F7FIVE0-Stream', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Exec(ExpandConstant('{sys}\net.exe'), 'stop F7FIVE0-API', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Result := '';
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  Cfg, CfgPath, Params, Lan: String;
  ResultCode: Integer;
begin
  if CurStep <> ssPostInstall then
    Exit;

  CfgPath := ExpandConstant('{tmp}\f7five0-setup.json');
  if NetPage.Values[0] then Lan := '1' else Lan := '0';
  Cfg := '{' + #13#10;
  if not IsUpgrade then
  begin
    Cfg := Cfg +
      JsonPair('adminUser', AdminPage.Values[0], False) +
      JsonPair('adminPassword', AdminPage.Values[1], False) +
      JsonPair('postgresPassword', PgPage.Values[0], False) +
      JsonPair('moviesDir', MediaPage.Values[0], False) +
      JsonPair('tvDir', MediaPage.Values[1], False) +
      JsonPair('musicDir', MediaPage.Values[2], False) +
      JsonPair('musicVideosDir', MediaPage.Values[3], False) +
      JsonPair('openFirewall', Lan, False) +
      JsonPair('webPort', Trim(PortsPage.Values[0]), False) +
      JsonPair('apiPort', Trim(PortsPage.Values[1]), False) +
      JsonPair('streamPort', Trim(PortsPage.Values[2]), False) +
      JsonPair('tmdbKey', Trim(OptionsPage.Values[0]), False);
  end;
  Cfg := Cfg + JsonPair('contactEmail', Trim(OptionsPage.Values[1]), True) + '}';
  SaveStringToFile(CfgPath, Cfg, False);

  Params := '-NoProfile -ExecutionPolicy Bypass -File "' + ExpandConstant('{app}\installer\install.ps1') +
    '" -InstallDir "' + ExpandConstant('{app}') + '" -ConfigFile "' + CfgPath + '" -NonInteractive';
  WizardForm.StatusLabel.Caption := 'Setting up F7FIVE0. A console window shows progress; this can take 10 minutes on a new PC...';
  if not Exec('powershell.exe', Params, ExpandConstant('{app}'), SW_SHOW, ewWaitUntilTerminated, ResultCode) or (ResultCode <> 0) then
  begin
    InstallFailed := True;
    MsgBox('F7FIVE0 setup did not finish (code ' + IntToStr(ResultCode) + ').' + #13#10#13#10 +
      'The log is in ' + ExpandConstant('{app}\logs') + '. Fix the problem it names and run Setup again; ' +
      'it picks up where it stopped.', mbError, MB_OK);
  end;
  DeleteFile(CfgPath);
end;

function SetupSucceeded: Boolean;
begin
  Result := not InstallFailed;
end;
